// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: models.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Atk {

  /// <summary>Holder for reflection information generated from models.proto</summary>
  public static partial class ModelsReflection {

    #region Descriptor
    /// <summary>File descriptor for models.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ModelsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cgxtb2RlbHMucHJvdG8SA2F0ayJpCgpDb3Vwb25JdGVtEgwKBE5hbWUYASAB",
            "KAkSDQoFUHJpY2UYAiABKAMSEAoIUXVhbnRpdHkYAyABKAISDQoFVG90YWwY",
            "BCABKAMSDwoHVGF4UmF0ZRgFIAEoCRIMCgRUeXBlGAYgASgJIjkKB1BheW1l",
            "bnQSHgoEVHlwZRgBIAEoDjIQLmF0ay5QYXltZW50VHlwZRIOCgZBbW91bnQY",
            "AiABKAMiQgoIVGF4R3JvdXASDwoHVGF4UmF0ZRgBIAEoCRITCgtUb3RhbEZv",
            "clRheBgCIAEoAxIQCghUb3RhbFRheBgDIAEoAyK5AgoJUG9zQ291cG9uEhIK",
            "CkJ1c2luZXNzSWQYASABKAQSDQoFVmF0SWQYAiABKAQSEAoIQ291cG9uSWQY",
            "AyABKAQSEAoITG9jYXRpb24YBCABKAkSEgoKT3BlcmF0b3JJZBgFIAEoCRIN",
            "CgVQb3NJZBgGIAEoBBIdCgRUeXBlGAcgASgOMg8uYXRrLkNvdXBvblR5cGUS",
            "DAoEVGltZRgIIAEoAxIeCgVJdGVtcxgJIAMoCzIPLmF0ay5Db3Vwb25JdGVt",
            "Eh4KCFBheW1lbnRzGAogAygLMgwuYXRrLlBheW1lbnQSDQoFVG90YWwYCyAB",
            "KAMSIAoJVGF4R3JvdXBzGAwgAygLMg0uYXRrLlRheEdyb3VwEhAKCFRvdGFs",
            "VGF4GA0gASgDEhIKClRvdGFsTm9UYXgYDiABKAMiwwEKDUNpdGl6ZW5Db3Vw",
            "b24SEgoKQnVzaW5lc3NJZBgBIAEoBBINCgVWYXRJZBgCIAEoBBIQCghDb3Vw",
            "b25JZBgDIAEoBBINCgVQb3NJZBgEIAEoBBIdCgRUeXBlGAUgASgOMg8uYXRr",
            "LkNvdXBvblR5cGUSDAoEVGltZRgGIAEoAxINCgVUb3RhbBgHIAEoAxIgCglU",
            "YXhHcm91cHMYCCADKAsyDS5hdGsuVGF4R3JvdXASEAoIVG90YWxUYXgYCSAB",
            "KAMivgEKCFFyQ291cG9uEhIKCkJ1c2luZXNzSWQYASABKAQSDQoFVmF0SWQY",
            "AiABKAQSEAoIQ291cG9uSWQYAyABKAQSDQoFUG9zSWQYBCABKAQSHQoEVHlw",
            "ZRgFIAEoDjIPLmF0ay5Db3Vwb25UeXBlEgwKBFRpbWUYBiABKAMSDQoFVG90",
            "YWwYByABKAMSIAoJVGF4R3JvdXBzGAggAygLMg0uYXRrLlRheEdyb3VwEhAK",
            "CFRvdGFsVGF4GAkgASgDKi4KCkNvdXBvblR5cGUSCAoEU2FsZRAAEgoKBkNh",
            "bmNlbBABEgoKBlJldHVybhACKmwKC1BheW1lbnRUeXBlEgsKB1Vua25vd24Q",
            "ABIICgRDYXNoEAESDgoKQ3JlZGl0Q2FyZBACEgsKB1ZvdWNoZXIQAxIKCgZD",
            "aGVxdWUQBBISCg5DcnlwdG9DdXJyZW5jeRAFEgkKBU90aGVyEAZCCVoHLi9w",
            "cm90b2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::Atk.CouponType), typeof(global::Atk.PaymentType), }, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Atk.CouponItem), global::Atk.CouponItem.Parser, new[]{ "Name", "Price", "Quantity", "Total", "TaxRate", "Type" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Atk.Payment), global::Atk.Payment.Parser, new[]{ "Type", "Amount" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Atk.TaxGroup), global::Atk.TaxGroup.Parser, new[]{ "TaxRate", "TotalForTax", "TotalTax" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Atk.PosCoupon), global::Atk.PosCoupon.Parser, new[]{ "BusinessId", "VatId", "CouponId", "Location", "OperatorId", "PosId", "Type", "Time", "Items", "Payments", "Total", "TaxGroups", "TotalTax", "TotalNoTax" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Atk.CitizenCoupon), global::Atk.CitizenCoupon.Parser, new[]{ "BusinessId", "VatId", "CouponId", "PosId", "Type", "Time", "Total", "TaxGroups", "TotalTax" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::Atk.QrCoupon), global::Atk.QrCoupon.Parser, new[]{ "BusinessId", "VatId", "CouponId", "PosId", "Type", "Time", "Total", "TaxGroups", "TotalTax" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CouponType {
    [pbr::OriginalName("Sale")] Sale = 0,
    [pbr::OriginalName("Cancel")] Cancel = 1,
    [pbr::OriginalName("Return")] Return = 2,
  }

  public enum PaymentType {
    [pbr::OriginalName("Unknown")] Unknown = 0,
    [pbr::OriginalName("Cash")] Cash = 1,
    [pbr::OriginalName("CreditCard")] CreditCard = 2,
    [pbr::OriginalName("Voucher")] Voucher = 3,
    [pbr::OriginalName("Cheque")] Cheque = 4,
    [pbr::OriginalName("CryptoCurrency")] CryptoCurrency = 5,
    [pbr::OriginalName("Other")] Other = 6,
  }

  #endregion

  #region Messages
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CouponItem : pb::IMessage<CouponItem>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CouponItem> _parser = new pb::MessageParser<CouponItem>(() => new CouponItem());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CouponItem> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atk.ModelsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CouponItem() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CouponItem(CouponItem other) : this() {
      name_ = other.name_;
      price_ = other.price_;
      quantity_ = other.quantity_;
      total_ = other.total_;
      taxRate_ = other.taxRate_;
      type_ = other.type_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CouponItem Clone() {
      return new CouponItem(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Price" field.</summary>
    public const int PriceFieldNumber = 2;
    private long price_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Price {
      get { return price_; }
      set {
        price_ = value;
      }
    }

    /// <summary>Field number for the "Quantity" field.</summary>
    public const int QuantityFieldNumber = 3;
    private float quantity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public float Quantity {
      get { return quantity_; }
      set {
        quantity_ = value;
      }
    }

    /// <summary>Field number for the "Total" field.</summary>
    public const int TotalFieldNumber = 4;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "TaxRate" field.</summary>
    public const int TaxRateFieldNumber = 5;
    private string taxRate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaxRate {
      get { return taxRate_; }
      set {
        taxRate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 6;
    private string type_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Type {
      get { return type_; }
      set {
        type_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CouponItem);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CouponItem other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Price != other.Price) return false;
      if (!pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.Equals(Quantity, other.Quantity)) return false;
      if (Total != other.Total) return false;
      if (TaxRate != other.TaxRate) return false;
      if (Type != other.Type) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Price != 0L) hash ^= Price.GetHashCode();
      if (Quantity != 0F) hash ^= pbc::ProtobufEqualityComparers.BitwiseSingleEqualityComparer.GetHashCode(Quantity);
      if (Total != 0L) hash ^= Total.GetHashCode();
      if (TaxRate.Length != 0) hash ^= TaxRate.GetHashCode();
      if (Type.Length != 0) hash ^= Type.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Price != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Price);
      }
      if (Quantity != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Quantity);
      }
      if (Total != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Total);
      }
      if (TaxRate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TaxRate);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Price != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Price);
      }
      if (Quantity != 0F) {
        output.WriteRawTag(29);
        output.WriteFloat(Quantity);
      }
      if (Total != 0L) {
        output.WriteRawTag(32);
        output.WriteInt64(Total);
      }
      if (TaxRate.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(TaxRate);
      }
      if (Type.Length != 0) {
        output.WriteRawTag(50);
        output.WriteString(Type);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Price != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Price);
      }
      if (Quantity != 0F) {
        size += 1 + 4;
      }
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      if (TaxRate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaxRate);
      }
      if (Type.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Type);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CouponItem other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Price != 0L) {
        Price = other.Price;
      }
      if (other.Quantity != 0F) {
        Quantity = other.Quantity;
      }
      if (other.Total != 0L) {
        Total = other.Total;
      }
      if (other.TaxRate.Length != 0) {
        TaxRate = other.TaxRate;
      }
      if (other.Type.Length != 0) {
        Type = other.Type;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Price = input.ReadInt64();
            break;
          }
          case 29: {
            Quantity = input.ReadFloat();
            break;
          }
          case 32: {
            Total = input.ReadInt64();
            break;
          }
          case 42: {
            TaxRate = input.ReadString();
            break;
          }
          case 50: {
            Type = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Price = input.ReadInt64();
            break;
          }
          case 29: {
            Quantity = input.ReadFloat();
            break;
          }
          case 32: {
            Total = input.ReadInt64();
            break;
          }
          case 42: {
            TaxRate = input.ReadString();
            break;
          }
          case 50: {
            Type = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class Payment : pb::IMessage<Payment>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Payment> _parser = new pb::MessageParser<Payment>(() => new Payment());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Payment> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atk.ModelsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payment() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payment(Payment other) : this() {
      type_ = other.type_;
      amount_ = other.amount_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Payment Clone() {
      return new Payment(this);
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::Atk.PaymentType type_ = global::Atk.PaymentType.Unknown;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atk.PaymentType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Amount" field.</summary>
    public const int AmountFieldNumber = 2;
    private long amount_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Amount {
      get { return amount_; }
      set {
        amount_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Payment);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Payment other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if (Amount != other.Amount) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != global::Atk.PaymentType.Unknown) hash ^= Type.GetHashCode();
      if (Amount != 0L) hash ^= Amount.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Type != global::Atk.PaymentType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Amount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Type != global::Atk.PaymentType.Unknown) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      if (Amount != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Amount);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Type != global::Atk.PaymentType.Unknown) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Amount != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Amount);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Payment other) {
      if (other == null) {
        return;
      }
      if (other.Type != global::Atk.PaymentType.Unknown) {
        Type = other.Type;
      }
      if (other.Amount != 0L) {
        Amount = other.Amount;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Type = (global::Atk.PaymentType) input.ReadEnum();
            break;
          }
          case 16: {
            Amount = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Type = (global::Atk.PaymentType) input.ReadEnum();
            break;
          }
          case 16: {
            Amount = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class TaxGroup : pb::IMessage<TaxGroup>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<TaxGroup> _parser = new pb::MessageParser<TaxGroup>(() => new TaxGroup());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<TaxGroup> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atk.ModelsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaxGroup() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaxGroup(TaxGroup other) : this() {
      taxRate_ = other.taxRate_;
      totalForTax_ = other.totalForTax_;
      totalTax_ = other.totalTax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public TaxGroup Clone() {
      return new TaxGroup(this);
    }

    /// <summary>Field number for the "TaxRate" field.</summary>
    public const int TaxRateFieldNumber = 1;
    private string taxRate_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string TaxRate {
      get { return taxRate_; }
      set {
        taxRate_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "TotalForTax" field.</summary>
    public const int TotalForTaxFieldNumber = 2;
    private long totalForTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalForTax {
      get { return totalForTax_; }
      set {
        totalForTax_ = value;
      }
    }

    /// <summary>Field number for the "TotalTax" field.</summary>
    public const int TotalTaxFieldNumber = 3;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as TaxGroup);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(TaxGroup other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (TaxRate != other.TaxRate) return false;
      if (TotalForTax != other.TotalForTax) return false;
      if (TotalTax != other.TotalTax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (TaxRate.Length != 0) hash ^= TaxRate.GetHashCode();
      if (TotalForTax != 0L) hash ^= TotalForTax.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (TaxRate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaxRate);
      }
      if (TotalForTax != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalForTax);
      }
      if (TotalTax != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (TaxRate.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(TaxRate);
      }
      if (TotalForTax != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(TotalForTax);
      }
      if (TotalTax != 0L) {
        output.WriteRawTag(24);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (TaxRate.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(TaxRate);
      }
      if (TotalForTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalForTax);
      }
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(TaxGroup other) {
      if (other == null) {
        return;
      }
      if (other.TaxRate.Length != 0) {
        TaxRate = other.TaxRate;
      }
      if (other.TotalForTax != 0L) {
        TotalForTax = other.TotalForTax;
      }
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            TaxRate = input.ReadString();
            break;
          }
          case 16: {
            TotalForTax = input.ReadInt64();
            break;
          }
          case 24: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            TaxRate = input.ReadString();
            break;
          }
          case 16: {
            TotalForTax = input.ReadInt64();
            break;
          }
          case 24: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class PosCoupon : pb::IMessage<PosCoupon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<PosCoupon> _parser = new pb::MessageParser<PosCoupon>(() => new PosCoupon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<PosCoupon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atk.ModelsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PosCoupon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PosCoupon(PosCoupon other) : this() {
      businessId_ = other.businessId_;
      vatId_ = other.vatId_;
      couponId_ = other.couponId_;
      location_ = other.location_;
      operatorId_ = other.operatorId_;
      posId_ = other.posId_;
      type_ = other.type_;
      time_ = other.time_;
      items_ = other.items_.Clone();
      payments_ = other.payments_.Clone();
      total_ = other.total_;
      taxGroups_ = other.taxGroups_.Clone();
      totalTax_ = other.totalTax_;
      totalNoTax_ = other.totalNoTax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public PosCoupon Clone() {
      return new PosCoupon(this);
    }

    /// <summary>Field number for the "BusinessId" field.</summary>
    public const int BusinessIdFieldNumber = 1;
    private ulong businessId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BusinessId {
      get { return businessId_; }
      set {
        businessId_ = value;
      }
    }

    /// <summary>Field number for the "VatId" field.</summary>
    public const int VatIdFieldNumber = 2;
    private ulong vatId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong VatId {
      get { return vatId_; }
      set {
        vatId_ = value;
      }
    }

    /// <summary>Field number for the "CouponId" field.</summary>
    public const int CouponIdFieldNumber = 3;
    private ulong couponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CouponId {
      get { return couponId_; }
      set {
        couponId_ = value;
      }
    }

    /// <summary>Field number for the "Location" field.</summary>
    public const int LocationFieldNumber = 4;
    private string location_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Location {
      get { return location_; }
      set {
        location_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "OperatorId" field.</summary>
    public const int OperatorIdFieldNumber = 5;
    private string operatorId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string OperatorId {
      get { return operatorId_; }
      set {
        operatorId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "PosId" field.</summary>
    public const int PosIdFieldNumber = 6;
    private ulong posId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PosId {
      get { return posId_; }
      set {
        posId_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 7;
    private global::Atk.CouponType type_ = global::Atk.CouponType.Sale;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atk.CouponType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 8;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Items" field.</summary>
    public const int ItemsFieldNumber = 9;
    private static readonly pb::FieldCodec<global::Atk.CouponItem> _repeated_items_codec
        = pb::FieldCodec.ForMessage(74, global::Atk.CouponItem.Parser);
    private readonly pbc::RepeatedField<global::Atk.CouponItem> items_ = new pbc::RepeatedField<global::Atk.CouponItem>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Atk.CouponItem> Items {
      get { return items_; }
    }

    /// <summary>Field number for the "Payments" field.</summary>
    public const int PaymentsFieldNumber = 10;
    private static readonly pb::FieldCodec<global::Atk.Payment> _repeated_payments_codec
        = pb::FieldCodec.ForMessage(82, global::Atk.Payment.Parser);
    private readonly pbc::RepeatedField<global::Atk.Payment> payments_ = new pbc::RepeatedField<global::Atk.Payment>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Atk.Payment> Payments {
      get { return payments_; }
    }

    /// <summary>Field number for the "Total" field.</summary>
    public const int TotalFieldNumber = 11;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "TaxGroups" field.</summary>
    public const int TaxGroupsFieldNumber = 12;
    private static readonly pb::FieldCodec<global::Atk.TaxGroup> _repeated_taxGroups_codec
        = pb::FieldCodec.ForMessage(98, global::Atk.TaxGroup.Parser);
    private readonly pbc::RepeatedField<global::Atk.TaxGroup> taxGroups_ = new pbc::RepeatedField<global::Atk.TaxGroup>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Atk.TaxGroup> TaxGroups {
      get { return taxGroups_; }
    }

    /// <summary>Field number for the "TotalTax" field.</summary>
    public const int TotalTaxFieldNumber = 13;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    /// <summary>Field number for the "TotalNoTax" field.</summary>
    public const int TotalNoTaxFieldNumber = 14;
    private long totalNoTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalNoTax {
      get { return totalNoTax_; }
      set {
        totalNoTax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as PosCoupon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(PosCoupon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BusinessId != other.BusinessId) return false;
      if (VatId != other.VatId) return false;
      if (CouponId != other.CouponId) return false;
      if (Location != other.Location) return false;
      if (OperatorId != other.OperatorId) return false;
      if (PosId != other.PosId) return false;
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if(!items_.Equals(other.items_)) return false;
      if(!payments_.Equals(other.payments_)) return false;
      if (Total != other.Total) return false;
      if(!taxGroups_.Equals(other.taxGroups_)) return false;
      if (TotalTax != other.TotalTax) return false;
      if (TotalNoTax != other.TotalNoTax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BusinessId != 0UL) hash ^= BusinessId.GetHashCode();
      if (VatId != 0UL) hash ^= VatId.GetHashCode();
      if (CouponId != 0UL) hash ^= CouponId.GetHashCode();
      if (Location.Length != 0) hash ^= Location.GetHashCode();
      if (OperatorId.Length != 0) hash ^= OperatorId.GetHashCode();
      if (PosId != 0UL) hash ^= PosId.GetHashCode();
      if (Type != global::Atk.CouponType.Sale) hash ^= Type.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      hash ^= items_.GetHashCode();
      hash ^= payments_.GetHashCode();
      if (Total != 0L) hash ^= Total.GetHashCode();
      hash ^= taxGroups_.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (TotalNoTax != 0L) hash ^= TotalNoTax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (VatId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(VatId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (OperatorId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OperatorId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Time);
      }
      items_.WriteTo(output, _repeated_items_codec);
      payments_.WriteTo(output, _repeated_payments_codec);
      if (Total != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(TotalTax);
      }
      if (TotalNoTax != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(TotalNoTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (VatId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(VatId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (Location.Length != 0) {
        output.WriteRawTag(34);
        output.WriteString(Location);
      }
      if (OperatorId.Length != 0) {
        output.WriteRawTag(42);
        output.WriteString(OperatorId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(48);
        output.WriteUInt64(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        output.WriteRawTag(56);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(64);
        output.WriteInt64(Time);
      }
      items_.WriteTo(ref output, _repeated_items_codec);
      payments_.WriteTo(ref output, _repeated_payments_codec);
      if (Total != 0L) {
        output.WriteRawTag(88);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(ref output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(104);
        output.WriteInt64(TotalTax);
      }
      if (TotalNoTax != 0L) {
        output.WriteRawTag(112);
        output.WriteInt64(TotalNoTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BusinessId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BusinessId);
      }
      if (VatId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VatId);
      }
      if (CouponId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CouponId);
      }
      if (Location.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Location);
      }
      if (OperatorId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(OperatorId);
      }
      if (PosId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      size += items_.CalculateSize(_repeated_items_codec);
      size += payments_.CalculateSize(_repeated_payments_codec);
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      size += taxGroups_.CalculateSize(_repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (TotalNoTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalNoTax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(PosCoupon other) {
      if (other == null) {
        return;
      }
      if (other.BusinessId != 0UL) {
        BusinessId = other.BusinessId;
      }
      if (other.VatId != 0UL) {
        VatId = other.VatId;
      }
      if (other.CouponId != 0UL) {
        CouponId = other.CouponId;
      }
      if (other.Location.Length != 0) {
        Location = other.Location;
      }
      if (other.OperatorId.Length != 0) {
        OperatorId = other.OperatorId;
      }
      if (other.PosId != 0UL) {
        PosId = other.PosId;
      }
      if (other.Type != global::Atk.CouponType.Sale) {
        Type = other.Type;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      items_.Add(other.items_);
      payments_.Add(other.payments_);
      if (other.Total != 0L) {
        Total = other.Total;
      }
      taxGroups_.Add(other.taxGroups_);
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      if (other.TotalNoTax != 0L) {
        TotalNoTax = other.TotalNoTax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            VatId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 42: {
            OperatorId = input.ReadString();
            break;
          }
          case 48: {
            PosId = input.ReadUInt64();
            break;
          }
          case 56: {
            Type = (global::Atk.CouponType) input.ReadEnum();
            break;
          }
          case 64: {
            Time = input.ReadInt64();
            break;
          }
          case 74: {
            items_.AddEntriesFrom(input, _repeated_items_codec);
            break;
          }
          case 82: {
            payments_.AddEntriesFrom(input, _repeated_payments_codec);
            break;
          }
          case 88: {
            Total = input.ReadInt64();
            break;
          }
          case 98: {
            taxGroups_.AddEntriesFrom(input, _repeated_taxGroups_codec);
            break;
          }
          case 104: {
            TotalTax = input.ReadInt64();
            break;
          }
          case 112: {
            TotalNoTax = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            VatId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 34: {
            Location = input.ReadString();
            break;
          }
          case 42: {
            OperatorId = input.ReadString();
            break;
          }
          case 48: {
            PosId = input.ReadUInt64();
            break;
          }
          case 56: {
            Type = (global::Atk.CouponType) input.ReadEnum();
            break;
          }
          case 64: {
            Time = input.ReadInt64();
            break;
          }
          case 74: {
            items_.AddEntriesFrom(ref input, _repeated_items_codec);
            break;
          }
          case 82: {
            payments_.AddEntriesFrom(ref input, _repeated_payments_codec);
            break;
          }
          case 88: {
            Total = input.ReadInt64();
            break;
          }
          case 98: {
            taxGroups_.AddEntriesFrom(ref input, _repeated_taxGroups_codec);
            break;
          }
          case 104: {
            TotalTax = input.ReadInt64();
            break;
          }
          case 112: {
            TotalNoTax = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class CitizenCoupon : pb::IMessage<CitizenCoupon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<CitizenCoupon> _parser = new pb::MessageParser<CitizenCoupon>(() => new CitizenCoupon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<CitizenCoupon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atk.ModelsReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CitizenCoupon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CitizenCoupon(CitizenCoupon other) : this() {
      businessId_ = other.businessId_;
      vatId_ = other.vatId_;
      couponId_ = other.couponId_;
      posId_ = other.posId_;
      type_ = other.type_;
      time_ = other.time_;
      total_ = other.total_;
      taxGroups_ = other.taxGroups_.Clone();
      totalTax_ = other.totalTax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public CitizenCoupon Clone() {
      return new CitizenCoupon(this);
    }

    /// <summary>Field number for the "BusinessId" field.</summary>
    public const int BusinessIdFieldNumber = 1;
    private ulong businessId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BusinessId {
      get { return businessId_; }
      set {
        businessId_ = value;
      }
    }

    /// <summary>Field number for the "VatId" field.</summary>
    public const int VatIdFieldNumber = 2;
    private ulong vatId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong VatId {
      get { return vatId_; }
      set {
        vatId_ = value;
      }
    }

    /// <summary>Field number for the "CouponId" field.</summary>
    public const int CouponIdFieldNumber = 3;
    private ulong couponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CouponId {
      get { return couponId_; }
      set {
        couponId_ = value;
      }
    }

    /// <summary>Field number for the "PosId" field.</summary>
    public const int PosIdFieldNumber = 4;
    private ulong posId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PosId {
      get { return posId_; }
      set {
        posId_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 5;
    private global::Atk.CouponType type_ = global::Atk.CouponType.Sale;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atk.CouponType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 6;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Total" field.</summary>
    public const int TotalFieldNumber = 7;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "TaxGroups" field.</summary>
    public const int TaxGroupsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Atk.TaxGroup> _repeated_taxGroups_codec
        = pb::FieldCodec.ForMessage(66, global::Atk.TaxGroup.Parser);
    private readonly pbc::RepeatedField<global::Atk.TaxGroup> taxGroups_ = new pbc::RepeatedField<global::Atk.TaxGroup>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Atk.TaxGroup> TaxGroups {
      get { return taxGroups_; }
    }

    /// <summary>Field number for the "TotalTax" field.</summary>
    public const int TotalTaxFieldNumber = 9;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as CitizenCoupon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(CitizenCoupon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BusinessId != other.BusinessId) return false;
      if (VatId != other.VatId) return false;
      if (CouponId != other.CouponId) return false;
      if (PosId != other.PosId) return false;
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if (Total != other.Total) return false;
      if(!taxGroups_.Equals(other.taxGroups_)) return false;
      if (TotalTax != other.TotalTax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BusinessId != 0UL) hash ^= BusinessId.GetHashCode();
      if (VatId != 0UL) hash ^= VatId.GetHashCode();
      if (CouponId != 0UL) hash ^= CouponId.GetHashCode();
      if (PosId != 0UL) hash ^= PosId.GetHashCode();
      if (Type != global::Atk.CouponType.Sale) hash ^= Type.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (Total != 0L) hash ^= Total.GetHashCode();
      hash ^= taxGroups_.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (VatId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(VatId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Total != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (VatId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(VatId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Total != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(ref output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BusinessId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BusinessId);
      }
      if (VatId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VatId);
      }
      if (CouponId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CouponId);
      }
      if (PosId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      size += taxGroups_.CalculateSize(_repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(CitizenCoupon other) {
      if (other == null) {
        return;
      }
      if (other.BusinessId != 0UL) {
        BusinessId = other.BusinessId;
      }
      if (other.VatId != 0UL) {
        VatId = other.VatId;
      }
      if (other.CouponId != 0UL) {
        CouponId = other.CouponId;
      }
      if (other.PosId != 0UL) {
        PosId = other.PosId;
      }
      if (other.Type != global::Atk.CouponType.Sale) {
        Type = other.Type;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.Total != 0L) {
        Total = other.Total;
      }
      taxGroups_.Add(other.taxGroups_);
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            VatId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 32: {
            PosId = input.ReadUInt64();
            break;
          }
          case 40: {
            Type = (global::Atk.CouponType) input.ReadEnum();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Total = input.ReadInt64();
            break;
          }
          case 66: {
            taxGroups_.AddEntriesFrom(input, _repeated_taxGroups_codec);
            break;
          }
          case 72: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            VatId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 32: {
            PosId = input.ReadUInt64();
            break;
          }
          case 40: {
            Type = (global::Atk.CouponType) input.ReadEnum();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Total = input.ReadInt64();
            break;
          }
          case 66: {
            taxGroups_.AddEntriesFrom(ref input, _repeated_taxGroups_codec);
            break;
          }
          case 72: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class QrCoupon : pb::IMessage<QrCoupon>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<QrCoupon> _parser = new pb::MessageParser<QrCoupon>(() => new QrCoupon());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<QrCoupon> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Atk.ModelsReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QrCoupon() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QrCoupon(QrCoupon other) : this() {
      businessId_ = other.businessId_;
      vatId_ = other.vatId_;
      couponId_ = other.couponId_;
      posId_ = other.posId_;
      type_ = other.type_;
      time_ = other.time_;
      total_ = other.total_;
      taxGroups_ = other.taxGroups_.Clone();
      totalTax_ = other.totalTax_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public QrCoupon Clone() {
      return new QrCoupon(this);
    }

    /// <summary>Field number for the "BusinessId" field.</summary>
    public const int BusinessIdFieldNumber = 1;
    private ulong businessId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong BusinessId {
      get { return businessId_; }
      set {
        businessId_ = value;
      }
    }

    /// <summary>Field number for the "VatId" field.</summary>
    public const int VatIdFieldNumber = 2;
    private ulong vatId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong VatId {
      get { return vatId_; }
      set {
        vatId_ = value;
      }
    }

    /// <summary>Field number for the "CouponId" field.</summary>
    public const int CouponIdFieldNumber = 3;
    private ulong couponId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong CouponId {
      get { return couponId_; }
      set {
        couponId_ = value;
      }
    }

    /// <summary>Field number for the "PosId" field.</summary>
    public const int PosIdFieldNumber = 4;
    private ulong posId_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong PosId {
      get { return posId_; }
      set {
        posId_ = value;
      }
    }

    /// <summary>Field number for the "Type" field.</summary>
    public const int TypeFieldNumber = 5;
    private global::Atk.CouponType type_ = global::Atk.CouponType.Sale;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Atk.CouponType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "Time" field.</summary>
    public const int TimeFieldNumber = 6;
    private long time_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Time {
      get { return time_; }
      set {
        time_ = value;
      }
    }

    /// <summary>Field number for the "Total" field.</summary>
    public const int TotalFieldNumber = 7;
    private long total_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long Total {
      get { return total_; }
      set {
        total_ = value;
      }
    }

    /// <summary>Field number for the "TaxGroups" field.</summary>
    public const int TaxGroupsFieldNumber = 8;
    private static readonly pb::FieldCodec<global::Atk.TaxGroup> _repeated_taxGroups_codec
        = pb::FieldCodec.ForMessage(66, global::Atk.TaxGroup.Parser);
    private readonly pbc::RepeatedField<global::Atk.TaxGroup> taxGroups_ = new pbc::RepeatedField<global::Atk.TaxGroup>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::Atk.TaxGroup> TaxGroups {
      get { return taxGroups_; }
    }

    /// <summary>Field number for the "TotalTax" field.</summary>
    public const int TotalTaxFieldNumber = 9;
    private long totalTax_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public long TotalTax {
      get { return totalTax_; }
      set {
        totalTax_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as QrCoupon);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(QrCoupon other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (BusinessId != other.BusinessId) return false;
      if (VatId != other.VatId) return false;
      if (CouponId != other.CouponId) return false;
      if (PosId != other.PosId) return false;
      if (Type != other.Type) return false;
      if (Time != other.Time) return false;
      if (Total != other.Total) return false;
      if(!taxGroups_.Equals(other.taxGroups_)) return false;
      if (TotalTax != other.TotalTax) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (BusinessId != 0UL) hash ^= BusinessId.GetHashCode();
      if (VatId != 0UL) hash ^= VatId.GetHashCode();
      if (CouponId != 0UL) hash ^= CouponId.GetHashCode();
      if (PosId != 0UL) hash ^= PosId.GetHashCode();
      if (Type != global::Atk.CouponType.Sale) hash ^= Type.GetHashCode();
      if (Time != 0L) hash ^= Time.GetHashCode();
      if (Total != 0L) hash ^= Total.GetHashCode();
      hash ^= taxGroups_.GetHashCode();
      if (TotalTax != 0L) hash ^= TotalTax.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (VatId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(VatId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Total != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (BusinessId != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(BusinessId);
      }
      if (VatId != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(VatId);
      }
      if (CouponId != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(CouponId);
      }
      if (PosId != 0UL) {
        output.WriteRawTag(32);
        output.WriteUInt64(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        output.WriteRawTag(40);
        output.WriteEnum((int) Type);
      }
      if (Time != 0L) {
        output.WriteRawTag(48);
        output.WriteInt64(Time);
      }
      if (Total != 0L) {
        output.WriteRawTag(56);
        output.WriteInt64(Total);
      }
      taxGroups_.WriteTo(ref output, _repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        output.WriteRawTag(72);
        output.WriteInt64(TotalTax);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (BusinessId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(BusinessId);
      }
      if (VatId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(VatId);
      }
      if (CouponId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(CouponId);
      }
      if (PosId != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(PosId);
      }
      if (Type != global::Atk.CouponType.Sale) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Time != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Time);
      }
      if (Total != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Total);
      }
      size += taxGroups_.CalculateSize(_repeated_taxGroups_codec);
      if (TotalTax != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(TotalTax);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(QrCoupon other) {
      if (other == null) {
        return;
      }
      if (other.BusinessId != 0UL) {
        BusinessId = other.BusinessId;
      }
      if (other.VatId != 0UL) {
        VatId = other.VatId;
      }
      if (other.CouponId != 0UL) {
        CouponId = other.CouponId;
      }
      if (other.PosId != 0UL) {
        PosId = other.PosId;
      }
      if (other.Type != global::Atk.CouponType.Sale) {
        Type = other.Type;
      }
      if (other.Time != 0L) {
        Time = other.Time;
      }
      if (other.Total != 0L) {
        Total = other.Total;
      }
      taxGroups_.Add(other.taxGroups_);
      if (other.TotalTax != 0L) {
        TotalTax = other.TotalTax;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            VatId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 32: {
            PosId = input.ReadUInt64();
            break;
          }
          case 40: {
            Type = (global::Atk.CouponType) input.ReadEnum();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Total = input.ReadInt64();
            break;
          }
          case 66: {
            taxGroups_.AddEntriesFrom(input, _repeated_taxGroups_codec);
            break;
          }
          case 72: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            BusinessId = input.ReadUInt64();
            break;
          }
          case 16: {
            VatId = input.ReadUInt64();
            break;
          }
          case 24: {
            CouponId = input.ReadUInt64();
            break;
          }
          case 32: {
            PosId = input.ReadUInt64();
            break;
          }
          case 40: {
            Type = (global::Atk.CouponType) input.ReadEnum();
            break;
          }
          case 48: {
            Time = input.ReadInt64();
            break;
          }
          case 56: {
            Total = input.ReadInt64();
            break;
          }
          case 66: {
            taxGroups_.AddEntriesFrom(ref input, _repeated_taxGroups_codec);
            break;
          }
          case 72: {
            TotalTax = input.ReadInt64();
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
